In [1]:
x=np.zeros((4,4))
print(x)

NameError: name 'np' is not defined

In [ ]:
x=np.zeros((4,4))

In [2]:
print(x)

NameError: name 'x' is not defined

In [ ]:
x = np.zeros((4,4))

In [3]:
print(x)

NameError: name 'x' is not defined

In [ ]:
import Numpy as np

In [ ]:
a = [10,20,30,40]

In [4]:
type(a)

NameError: name 'a' is not defined

In [5]:
print(a)

NameError: name 'a' is not defined

In [6]:
a=[10,20,30,40]
type(a)

list

In [ ]:
a=[10,20,30,40]

In [7]:
type(a)

list

In [8]:
x=np.array(a)

NameError: name 'np' is not defined

In [9]:
print(x)

NameError: name 'x' is not defined

In [ ]:
x=np.array(a)

In [10]:
print(x)

NameError: name 'x' is not defined

In [11]:
x=np.array(a)
print(x)

NameError: name 'np' is not defined

In [12]:
import numpy as np
a=[10,20,30,40]
type(a)

list

In [13]:
x=np.array(a)
print(x)

[10 20 30 40]


In [14]:
type(x)|

SyntaxError: invalid syntax (3401597118.py, line 1)

In [15]:
x=np.array(a)
type(x)

numpy.ndarray

# a=[1,2,3,4]
b=[10,20,30,40,50]
x=np.array(a,b)

In [18]:
a=[1,2,3,4]
b=[10,20,30,40]
x=np.array([a,b])
print(x)

[[ 1  2  3  4]
 [10 20 30 40]]


In [19]:
a=[1,2,3,4]
b=[10,20,30,40]
x=np.array(a,b)
print(x)

TypeError: Field elements must be 2- or 3-tuples, got '10'

In [20]:
x=np.array[1,2,3,4],dtype=np.float32)
print(x)

SyntaxError: unmatched ')' (3793232329.py, line 1)

In [ ]:
x=np.array[1,2,3,4]
dtype=np.array